import Head from "next/head";
import "./globals.css";

import Navbar from "./componets/nav/nav";
import Footer from "./componets/footer/footer";

export const metadata = {
  title: "Malpo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <Head>         
        </Head>
        <body className="lato-regular">
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </>
  );
}
